DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ NOCACHE;

DROP TABLE MEMBER;
CREATE TABLE MEMBER (
    MEMBER_NO   NUMBER              NOT NULL,
    ID          VARCHAR2(30 BYTE)   NOT NULL,
    PW          VARCHAR2(20 BYTE)   NOT NULL,
    NAME        VARCHAR2(100 BYTE)  NOT NULL,
    EMAIL       VARCHAR2(100 BYTE),
    PHONE_NUMBER VARCHAR2(13 BYTE),
    ADDRESS     VARCHAR2(300 BYTE),
    CONSTRAINT PK_MEMBER PRIMARY KEY(MEMBER_NO)
);

INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'admin', '1111', '관리자', 'admin@winenara.com', '010-1234-1234', '와인시 소주구 맥주동 알콜아파트 111호');

COMMIT;